"""add_status_to_documents

Revision ID: 7a50ebcc5496
Revises: b9c3d2e1f0a4
Create Date: 2026-05-30 20:08:14.651026

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a50ebcc5496'
down_revision: Union[str, Sequence[str], None] = 'b9c3d2e1f0a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('training_documents', sa.Column('status', sa.String(), nullable=True))
    op.execute("UPDATE training_documents SET status = 'done' WHERE status IS NULL")
    op.alter_column('training_documents', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('training_documents', 'status')
    # ### end Alembic commands ###
